---
- name: install postgres
  apt: name={{ item }} state=present
  with_items:
    - postgresql-contrib-{{ pg_version }}
    - postgresql-server-dev-{{ pg_version }}
    - postgresql-client-{{ pg_version }}
    - libpq-dev
    - postgresql-{{ pg_version }}
    - python-psycopg2

- name: remove the postgres meta-package
  apt: name=postgresql state=absent

- name: ensure postgres is running
  service: name=postgresql state=started

# The postgres < 9.3 problem with the default encoding not being utf8
# isn't a problem with Ansible >= 1.6.  Hopefully.
# ref: https://github.com/ansible/ansible/issues/7246

- name: create the project postgres user
  postgresql_user: name="{{ db_user }}"
                   role_attr_flags=NOCREATEDB,NOCREATEROLE,NOSUPERUSER
                   password="{{ db_password }}"
                   encrypted=yes
  become_user: postgres

- name: create the project database
  postgresql_db: name="{{ db_name }}"
                 owner="{{ db_user }}"
                 state=present
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'
  become_user: postgres

- name: configure postgres authentication
  template: src="pg_hba.conf"
            dest=/etc/postgresql/{{ pg_version }}/main/pg_hba.conf
            owner=postgres group=postgres mode=0640
  notify:
    - reload postgres

- name: configure postgres
  template: src="postgresql.conf"
            dest=/etc/postgresql/{{ pg_version }}/main/postgresql.conf
            owner=postgres group=postgres mode=0644
  notify:
    - restart postgres

- name: allow app minions through the firewall
  ufw: rule=allow port=5432 from_ip={{ hostvars[item].ansible_eth0.ipv4.address }}
  with_items: app_minions
